### ISSUE TITLE
краш

### ISSUE THREAD

**Issue by SachaTending** [xzxADIxzx/Useful-Stuffs#4]
при нажатию на кнопку которая должна закрыть меню, у клиента происхожит ошибка
`[E] java.lang.NullPointerException: Parameter specified as non-null is null: method mindustry.client.communication.InvisibleCharCoder.strip, parameter inp
	at mindustry.client.communication.InvisibleCharCoder.strip(InvisibleCharCoder.kt)
	at mindustry.core.NetClient.sendMessage(NetClient.java:247)
	at mindustry.gen.SendMessageCallPacket2.handleClient(SendMessageCallPacket2.java:40)
	at mindustry.net.Net.handleClientReceived(Net.java:295)
	at mindustry.net.ArcNetProvider$1.lambda$received$2(ArcNetProvider.java:83)
	at arc.util.TaskQueue.run(TaskQueue.java:17)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:195)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:57)`

**Comment by xzxADIxzx** [comment]
@Darkness6030 это к тебе

**Comment by xzxADIxzx** [comment]
@Darkness6030 ну ёмоё, разберись, меню-то твои

**Comment by Darkness6030** [comment]
Возникает из-за несоответствия пакетов и кривых модов, не имеет никакого отношения к либе.
